group/urls.py
from django.contrib import admin
from django.urls import path
#from django.conf.urls import url, include
# from LOGIN import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from LOGIN.views import UserReg, sharing, discussion, view, workshop, booking, member
from .import views
#from django.conf.urls import url
from .views import *

# from .api import UserList, UserDetail, UserAuthentication

app_name = 'group'
urlpatterns = [
    path('MainGroup',views.mainGroup, name="MainGroup"),
    path('AddGroup',views.AddGroup, name="AddGroup"),
    path('MyGroup',views.myGroup, name="MyGroup"),
    path('ViewGroup/<str:pk>',views.viewGroup, name="ViewGroup"),
    path('JoinGroup/<str:pk>',views.joinGroup, name="JoinGroup"),
    path('DeleteGroup/<str:pk>',views.deleteGroup, name="DeleteGroup"),
    path('UpdateGroup/<str:pk>',views.updateGroup, name="UpdateGroup"),
    path('AddGroupSharing/<str:pk>',views.AddGroupSharing, name="AddGroupSharing"),
    path('Filter_SoilTag',views.Group_SoilTag, name="Group_SoilTag"),
    path('Filter_PlantTag',views.Group_PlantTag, name="Group_PlantTag"),
    path('GroupSharingComment/<str:pk>',views.addGSComment, name="GroupSharingComment"),
    path('PL-Sharing/<str:pk>', views.PLSharing, name="PL-Sharing"),
    path('PlantLink-Graph-API', views.PLGraphAPI, name="PlantLink-Graph-API"),
 

] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

marketplace/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import re_path as url, include
# from LOGIN import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from LOGIN.views import UserReg, sharing, discussion, view, workshop, booking, member
from .import views
# from .import index
from .views import *
# from .api import UserList, UserDetail, UserAuthentication

app_name = 'marketplace'
urlpatterns = [
    path('MainMarketplace',views.mainMarketplace, name="MainMarketplace"),
    path('SellProduct.html/<str:fk1>/',views.sellProduct, name="SellProduct"),
    path('DeleteProduct/<str:fk1>/',views.deleteProduct, name="DeleteProduct"),
    path('UpdateProduct.html/<str:fk1>/',views.updateProduct, name="UpdateProduct"),
    path('MyMarketplace',views.myMarketplace, name="MyMarketplace"),
    path('buy_now/<str:fk1>/<str:fk2>/',views.buy_now, name='buy_now'),
    path('add_to_basket/<str:fk1>/<str:fk2>/',views.add_to_basket, name='add_to_basket'),
    path('ViewProduct/<str:pk>',views.viewProduct, name="viewProduct"),
    path('ViewSeller/<str:pk>',views.viewSeller, name="viewSeller"),
    path('RestrictProduct/<str:fk1>/',views.restrictProduct, name="restrictProduct"),
    path('UnrestrictProduct/<str:fk1>/',views.unrestrictProduct, name="unrestrictProduct")

] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

plantfeed/urls.py
from member import views
from sharing import views
from group import views
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', views.index ),
    path('', include('member.urls')),
    path('sharing/', include('sharing.urls')),
    path('group/', include('group.urls')),
    path('workshop/', include('workshop.urls')),
    path('marketplace/', include('marketplace.urls')),
    path('suggestion/', include('suggestion.urls')),
    path('basket/', include('basket.urls')),
    path('topic/', include('topic.urls')),
    path('payment/', include('payment.urls')),
    path('orders/', include('orders.urls')),
    path('paymentAPI/', include('paymentAPI.urls')),
    #path('api-auth/', include('rest_framework.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('plantlink/Login/', views.authenticate_user, name='authenticate_user'),
]

sharing/urls.py
from django.contrib import admin
from django.urls import path
#from django.conf.urls import url, include
# from LOGIN import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from LOGIN.views import UserReg, sharing, discussion, view, workshop, booking, member
from .import views
#from django.conf.urls import url
from .views import *
from .import api

# from .api import UserList, UserDetail, UserAuthentication

app_name = 'sharing'
urlpatterns = [
    #path('MainSharing',views.mainSharing, name="MainSharing"),
    #path('SharingGroup/<str:pk>',views.sharingGroup, name="SharingGroup"),
    path('UpdateSharing/<str:pk>',views.updateSharing, name="UpdateSharing"),
    path('DeleteSharing/<str:pk>', views.deleteSharing, name="DeleteSharing"),
    path('Forum/<str:pk>', views.viewForum, name="Forum"),
    path('MainSharing',views.mainSharing, name="MainSharing"),
    path('AddNewSharing',views.AddSharing, name="AddSharing"),
    
    #path(',../MainPageSharing.html/<str:pk>', views.addLikes, name="AddLikes"),
    path('AddComment/<str:pk>', views.addComment, name="AddComment"),
    path('UpdateComment/<str:pk>',views.updateComment, name="UpdateComment"),
    path('DeleteComment/<str:pk>', views.deleteComment, name="DeleteComment"),
    path('AddLikes/<str:pk>', views.AddLikes, name="AddLikes"),
    

    path('MainSharing/Sharing_SoilTag',views.Sharing_SoilTag, name="Sharing_SoilTag"),
    path('MainSharing/Sharing_PlantTag',views.Sharing_PlantTag, name="Sharing_PlantTag"),
    # path('Sharing_PlantTag',views.Sharing_GeneralPlantTag, name="Sharing_GeneralPlantTag"),
    # path('Sharing_PlantTag/<str:plantTag>',views.Sharing_PlantTag, name="Sharing_PlantTag"),
    path('users/post-feed/', api.postFeed),
    path('users/feed/<int:creator_id>/', api.CreatorFeedView.as_view(), name='creator_feed'),


] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

workshop/urls.py
from django.contrib import admin
from django.urls import path
#from django.conf.urls import url, include
# from LOGIN import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from LOGIN.views import UserReg, sharing, discussion, view, workshop, booking, member
from .import views
#from django.conf.urls import url
# from .import index

# from .api import UserList, UserDetail, UserAuthentication

app_name = 'workshop'
urlpatterns = [
    
    path('MainWorkshop',views.workshop, name="MainWorkshop"),
    path('Booking',views.booking, name="Booking"),
    path('Booking/<str:pk>',views.booking, name="Booking"),
    path('CreateWorkshop',views.createWorkshop, name="CreateWorkshop"),
    path('UpdateWorkshop/<str:pk>',views.updateWorkshop, name="UpdateWorkshop"),
    path('DeleteWorkshop/<str:pk>',views.deleteWorkshop, name="DeleteWorkshop"),
    path('ViewWorkshop/<str:pk>',views.viewWorkshop, name="ViewWorkshop"),
    path('MyWorkshop',views.myWorkshop, name="MyWorkshop"),
    path('MyBooking',views.viewBooking, name="MyBooking"),
    path('ViewInbox', views.viewInbox, name="ViewInbox"),
    path('CancelBooking/<str:pk>',views.deleteBooking, name="DeleteBooking"),
    path('WorkshopParticipant/<str:id>',views.WorkshopParticipant, name="WorkshopParticipant"),
    path('AddWorkshopSharing/<str:pk>',views.AddWorkshopSharing, name="AddWorkshopSharing"),
    path('Filter_SoilTag',views.Workshop_SoilTag, name="Workshop_SoilTag"),
    path('Filter_PlantTag',views.Workshop_PlantTag, name="Workshop_PlantTag"),
    # path('Workshop_LocationTag',views.Workshop_LocationTag, name="Workshop_LocationTag"),
    # path('Workshop_DemographicTag',views.Workshop_DemographicTag, name="Workshop_DemographicTag"),
    #path('Location',views.Location, name="Location"),


] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

group/models.py
from django.db import models, migrations
# from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from django.conf import settings
from django.db.models.signals import post_save
from django.contrib.syndication.views import Feed
from member.models import Person, SoilTag, PlantTag

# Create your models here.

class Group_tbl(models.Model):
    
    Name = models.CharField(max_length=150)
    About = models.CharField(max_length=1000)
    Media = models.ImageField(upload_to='uploads/',default="")
    Username = models.ForeignKey(Person, on_delete=models.CASCADE)
    Age = models.CharField(max_length=100,default="")
    State = models.CharField(max_length=100,default="")

    def save(self):
        # group = self
        super().save()
        #super().save(using='farming')
        # return group
        return self.id
    
    
        
    def deleteRecordIgrow(self):
        super().delete()
    
    class Meta:
        db_table = 'group_tbl'
        
class pl_graph_api(models.Model):
    
    name = models.CharField(max_length=255)
    embed_link = models.CharField(max_length=255)
    chart_type = models.CharField(max_length=255)
    start_date = models.DateTimeField(default=timezone.now)
    end_date = models.DateTimeField(default=timezone.now)
    Person_fk = models.ForeignKey(Person, on_delete=models.CASCADE)
    
    def save(self):
        super().save()
        
class pl_graph_sharing(models.Model):
    
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=1500)
    link = models.CharField(max_length=255)
    chart_type = models.CharField(max_length=255, null=True)
    Group_fk = models.ForeignKey(Group_tbl, on_delete=models.CASCADE)
    Person_fk = models.ForeignKey(Person, on_delete=models.CASCADE)
    
    def save(self):
        super().save()

class GroupMembership(models.Model):
    
    GroupName = models.ForeignKey(Group_tbl, on_delete=models.CASCADE)
    GroupMember = models.ForeignKey(Person, on_delete=models.CASCADE)
    # joined_on = models.DateTimeField(default=datetime.now, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True, blank=True)

    def save(self):
        super().save()

    
    class Meta:
        
        unique_together = [['GroupName', 'GroupMember']]


class GroupSoilTagging(models.Model):

    GroupSoilTag = models.ForeignKey(Group_tbl, related_name="soilTagging", on_delete=models.CASCADE)    
    soilTag = models.ForeignKey(SoilTag, on_delete=models.CASCADE)
   
    class Meta:  
        unique_together = [['GroupSoilTag', 'soilTag']]

    def save(self):
        super().save()
   
    def deleteRecordIgrow(self):
        super().delete()


class GroupPlantTagging(models.Model):

    GroupPlantTag = models.ForeignKey(Group_tbl, related_name="plantTagging", on_delete=models.CASCADE)    
    plantTag = models.ForeignKey(PlantTag, on_delete=models.CASCADE)
   
    class Meta:  
        unique_together = [['GroupPlantTag', 'plantTag']]

    def save(self):
        super().save()
   
    def deleteRecordIgrow(self):
        super().delete()

group/forms.py
from django import forms
from .models import Group_tbl


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group_tbl
        fields = ('Name', 'About', 'Media')

group/templates/PlantFilteredGroup.html
<!doctype html>
<html lang="en">

<head>
  <style>
    .content {
      max-width: 500px;
      margin: auto;
    }

    table {
      border: 4px solid black;
      margin: 0 auto;
      padding: 40px;
      width: fit-content;
      
    }

    .panel {
    margin-bottom: 30px;
    color: #696969;
    background-color: #fff;
    border-radius: 5px;
    box-shadow: 0 1px 5px rgba(0, 0, 0, 0.08);
}
  </style>
</head>

<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
  integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

<!-- <h1 class="p-3 mb-2 bg-success text-white text-center">iGROW Knowledge Management System</h1> -->

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
  integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
  integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js"
  integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>



<div class="pos-f-t">
  <div class="collapse" id="navbarToggleExternalContent">
    <div class="p-4" style="background-color: #8FBC8F;">
      <h4 class="text-white">What are you looking for?</h4>
      <span class="text-muted">Search here...</span>
      <form class="form-inline my-2">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-primary" type="submit">Search</button>
      </form>
    </div>
    
  </div>
  <nav class="navbar navbar-dark bg-success">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </nav>
</div>

<nav class="navbar navbar-expand navbar-dark bg-success">
  <a class="navbar-brand" href="#">P  L  A  N  T  F  E  E  D</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link " href="{% url 'Home' %}">Home</a>
      </li>
      {% if person.UserLevel == 'user' %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'sharing:MainSharing' %}">Sharing</a>
      </li>
      {% endif %}
      </li>
            <li class="nav-item">
        <a class="nav-link active" href=" {% url 'group:MainGroup' %}">Group</a>
      </li>
      {% if person.UserLevel == 'user' %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'MemberMainPage' %}">Member</a>
      </li>
      {% endif %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'workshop:MainWorkshop' %}">Workshop</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Marketplace
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'marketplace:MainMarketplace' %}">Browse Marketplace<span class="sr-only">(current)</span></a>
          <a class="dropdown-item" href="{% url 'marketplace:MyMarketplace' %}">My Marketplace</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Profile
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'ViewProfile' %}">View Profile<span class="sr-only">(current)</span></a>
          <a class="dropdown-item" href="{% url 'EditProfile' %}">Edit Profile</a>
        </div>
      </li>

    </ul>
    <a class="btn bg-light" href="{% url 'Logout' %}">
      <img class="bi bi-arrow-bar-right">LOGOUT</img>
    </a>
  </div>
</nav>
<br />

  {% block content %}
  <div class="container">
    <div class="row">
      <div class="col-sm">
        <div class="container">
          <div class="row">
            <div class="col-8">
              <body>  
                {% csrf_token %}
                          <div class="container my-3 bg-light">
                            <label for="exampleFormControlTextarea1" style="font-size: 2em;" >Group</label>
                          </div>
  
                          <div class="col-12">
                            <a class="btn btn-primary" href="{% url 'group:AddGroup' %}" role="button">New Group</a>
                          
                            <a class="btn btn-primary" href="{% url 'group:MyGroup' %}" role="button">My Group</a>
                          </div>
                          <br/>
                          <div class="container"><h9>Filter based on tags: {{chosen_plantTag.PlantTagName}}</h9></div>
                          <br/>
                          {% endblock content %}
                          

<form action="{% url 'group:AddGroup' %}" method="POST" class="center">
  {% csrf_token %}
  {{ form.as_p }}
        <div class="container">
          <div class="row">
            <table class="table caption-top">
              <thead>
                <tr>
                  <th scope="col">Name</th>
                  <th scope="col">About</th>
                  <th scope="col">Media</th>
                  <th scope="col">Owner</th>
                  <th scope="col">Tagging Detail</th>
                  <th scope="col">Action</th>
                  
                </tr>
              </thead>
              <tbody>
                {% for group in filteredGroup %}
                <tr>
                  <th scope="row" value="{{ group.GroupPlantTag.Name }}">{{ group.GroupPlantTag.Name }}</th>
                  <th scope="row" value="{{ group.GroupPlantTag.About }}">{{ group.GroupPlantTag.About }}</th>              
                  <th><img src="../media/{{group.GroupPlantTag.Media}}" width="120" /></th>
                  <th scope="row" <a href="{{ group.GroupPlantTag.Username.Name }}">{{ group.GroupPlantTag.Username.Name }}</a></th>
                  <th>
                      {%for ori_group in ori_group %}

                      {% if group.GroupPlantTag == ori_group %}

                        {% if ori_group.soilTagging.all %}
                            
                            <i>
                            {% for soilTags in ori_group.soilTagging.all %}
                            {{soilTags.soilTag.SoilTagName}}  {% if not forloop.last %},{% endif %} 
                            {% endfor %}
                          </i>
                        {% endif %}

                        {% if ori_group.plantTagging.all %}
                          
                          <i>
                          {% for plantTags in ori_group.plantTagging.all %}
                          {{plantTags.plantTag.PlantTagName}}  {% if not forloop.last %},{% endif %} 
                          {% endfor %}
                        </i>            
                        {% endif %}

                      {% endif %}

                      {% endfor %} 
                  </th>
                  {% if group.GroupPlantTag.Username.Email != request.session.Email %}
                  <th>
                    <a href="{% url 'group:JoinGroup' group.GroupPlantTag.id %}" class="card-link">Join</a>
                  </th>
                  {% else %}
                  <th>&nbsp; </th>
                  {% endif %}
                </tr>
                {% endfor %}
              </tbody>
            </table>
      </div>
</form>

{% if not filteredGroup %}
<div class="container">
    <h7 style="text-align: center;"><i>No group related to this {{ chosen_plantTag.PlantTagName }} tag </i></h7>
</div>
{% endif %}

<hr>
{% if messages %}
{% for msg in messages %}
<b>{{msg}}</b><br/>
{% endfor %}
{% endif %}
<hr />
{% endblock body %}
   </html>