group/urls.py
from django.contrib import admin
from django.urls import path
#from django.conf.urls import url, include
# from LOGIN import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from LOGIN.views import UserReg, sharing, discussion, view, workshop, booking, member
from .import views
#from django.conf.urls import url
from .views import *

# from .api import UserList, UserDetail, UserAuthentication

app_name = 'group'
urlpatterns = [
    path('MainGroup',views.mainGroup, name="MainGroup"),
    path('AddGroup',views.AddGroup, name="AddGroup"),
    path('MyGroup',views.myGroup, name="MyGroup"),
    path('ViewGroup/<str:pk>',views.viewGroup, name="ViewGroup"),
    path('JoinGroup/<str:pk>',views.joinGroup, name="JoinGroup"),
    path('DeleteGroup/<str:pk>',views.deleteGroup, name="DeleteGroup"),
    path('UpdateGroup/<str:pk>',views.updateGroup, name="UpdateGroup"),
    path('AddGroupSharing/<str:pk>',views.AddGroupSharing, name="AddGroupSharing"),
    path('Filter_SoilTag',views.Group_SoilTag, name="Group_SoilTag"),
    path('Filter_PlantTag',views.Group_PlantTag, name="Group_PlantTag"),
    path('GroupSharingComment/<str:pk>',views.addGSComment, name="GroupSharingComment"),
    path('PL-Sharing/<str:pk>', views.PLSharing, name="PL-Sharing"),
    path('PlantLink-Graph-API', views.PLGraphAPI, name="PlantLink-Graph-API"),
 

] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

marketplace/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import re_path as url, include
# from LOGIN import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from LOGIN.views import UserReg, sharing, discussion, view, workshop, booking, member
from .import views
# from .import index
from .views import *
# from .api import UserList, UserDetail, UserAuthentication

app_name = 'marketplace'
urlpatterns = [
    path('MainMarketplace',views.mainMarketplace, name="MainMarketplace"),
    path('SellProduct.html/<str:fk1>/',views.sellProduct, name="SellProduct"),
    path('DeleteProduct/<str:fk1>/',views.deleteProduct, name="DeleteProduct"),
    path('UpdateProduct.html/<str:fk1>/',views.updateProduct, name="UpdateProduct"),
    path('MyMarketplace',views.myMarketplace, name="MyMarketplace"),
    path('buy_now/<str:fk1>/<str:fk2>/',views.buy_now, name='buy_now'),
    path('add_to_basket/<str:fk1>/<str:fk2>/',views.add_to_basket, name='add_to_basket'),
    path('ViewProduct/<str:pk>',views.viewProduct, name="viewProduct"),
    path('ViewSeller/<str:pk>',views.viewSeller, name="viewSeller"),
    path('RestrictProduct/<str:fk1>/',views.restrictProduct, name="restrictProduct"),
    path('UnrestrictProduct/<str:fk1>/',views.unrestrictProduct, name="unrestrictProduct")

] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

plantfeed/urls.py
from member import views
from sharing import views
from group import views
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', views.index ),
    path('', include('member.urls')),
    path('sharing/', include('sharing.urls')),
    path('group/', include('group.urls')),
    path('workshop/', include('workshop.urls')),
    path('marketplace/', include('marketplace.urls')),
    path('suggestion/', include('suggestion.urls')),
    path('basket/', include('basket.urls')),
    path('topic/', include('topic.urls')),
    path('payment/', include('payment.urls')),
    path('orders/', include('orders.urls')),
    path('paymentAPI/', include('paymentAPI.urls')),
    #path('api-auth/', include('rest_framework.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('plantlink/Login/', views.authenticate_user, name='authenticate_user'),
]

sharing/urls.py
from django.contrib import admin
from django.urls import path
#from django.conf.urls import url, include
# from LOGIN import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from LOGIN.views import UserReg, sharing, discussion, view, workshop, booking, member
from .import views
#from django.conf.urls import url
from .views import *
from .import api

# from .api import UserList, UserDetail, UserAuthentication

app_name = 'sharing'
urlpatterns = [
    #path('MainSharing',views.mainSharing, name="MainSharing"),
    #path('SharingGroup/<str:pk>',views.sharingGroup, name="SharingGroup"),
    path('UpdateSharing/<str:pk>',views.updateSharing, name="UpdateSharing"),
    path('DeleteSharing/<str:pk>', views.deleteSharing, name="DeleteSharing"),
    path('Forum/<str:pk>', views.viewForum, name="Forum"),
    path('MainSharing',views.mainSharing, name="MainSharing"),
    path('AddNewSharing',views.AddSharing, name="AddSharing"),
    
    #path(',../MainPageSharing.html/<str:pk>', views.addLikes, name="AddLikes"),
    path('AddComment/<str:pk>', views.addComment, name="AddComment"),
    path('UpdateComment/<str:pk>',views.updateComment, name="UpdateComment"),
    path('DeleteComment/<str:pk>', views.deleteComment, name="DeleteComment"),
    path('AddLikes/<str:pk>', views.AddLikes, name="AddLikes"),
    

    path('MainSharing/Sharing_SoilTag',views.Sharing_SoilTag, name="Sharing_SoilTag"),
    path('MainSharing/Sharing_PlantTag',views.Sharing_PlantTag, name="Sharing_PlantTag"),
    # path('Sharing_PlantTag',views.Sharing_GeneralPlantTag, name="Sharing_GeneralPlantTag"),
    # path('Sharing_PlantTag/<str:plantTag>',views.Sharing_PlantTag, name="Sharing_PlantTag"),
    path('users/post-feed/', api.postFeed),
    path('users/feed/<int:creator_id>/', api.CreatorFeedView.as_view(), name='creator_feed'),


] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

workshop/urls.py
from django.contrib import admin
from django.urls import path
#from django.conf.urls import url, include
# from LOGIN import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from LOGIN.views import UserReg, sharing, discussion, view, workshop, booking, member
from .import views
#from django.conf.urls import url
# from .import index

# from .api import UserList, UserDetail, UserAuthentication

app_name = 'workshop'
urlpatterns = [
    
    path('MainWorkshop',views.workshop, name="MainWorkshop"),
    path('Booking',views.booking, name="Booking"),
    path('Booking/<str:pk>',views.booking, name="Booking"),
    path('CreateWorkshop',views.createWorkshop, name="CreateWorkshop"),
    path('UpdateWorkshop/<str:pk>',views.updateWorkshop, name="UpdateWorkshop"),
    path('DeleteWorkshop/<str:pk>',views.deleteWorkshop, name="DeleteWorkshop"),
    path('ViewWorkshop/<str:pk>',views.viewWorkshop, name="ViewWorkshop"),
    path('MyWorkshop',views.myWorkshop, name="MyWorkshop"),
    path('MyBooking',views.viewBooking, name="MyBooking"),
    path('ViewInbox', views.viewInbox, name="ViewInbox"),
    path('CancelBooking/<str:pk>',views.deleteBooking, name="DeleteBooking"),
    path('WorkshopParticipant/<str:id>',views.WorkshopParticipant, name="WorkshopParticipant"),
    path('AddWorkshopSharing/<str:pk>',views.AddWorkshopSharing, name="AddWorkshopSharing"),
    path('Filter_SoilTag',views.Workshop_SoilTag, name="Workshop_SoilTag"),
    path('Filter_PlantTag',views.Workshop_PlantTag, name="Workshop_PlantTag"),
    # path('Workshop_LocationTag',views.Workshop_LocationTag, name="Workshop_LocationTag"),
    # path('Workshop_DemographicTag',views.Workshop_DemographicTag, name="Workshop_DemographicTag"),
    #path('Location',views.Location, name="Location"),


] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

workshop/models.py
from datetime import datetime
from django.db import models, migrations
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.contrib.syndication.views import Feed
from member.models import Person, SoilTag, PlantTag

# Create your models here.

class Workshop(models.Model):
    class Meta:
        db_table = 'Workshop'
    ProgrammeName = models.CharField(max_length=150,default="")
    Speaker=models.CharField(max_length=150, default="")
    Description=models.CharField(max_length=150,default="")
    Date = models.DateField()
    RegistrationDue = models.DateField()
    Gender = models.CharField(max_length=20,default="")
    StartTime = models.TimeField()
    EndTime = models.TimeField()
    State = models.CharField(max_length=100,default="")
    Venue = models.CharField(max_length=100,default="")
    Poster = models.ImageField(upload_to='uploads/',default="")
    #RegistrationDue = models.DateField()
    # Session = models.CharField(max_length=150)
    # nanti next version or bila share version ni, sila remove null=true okay
    PIC = models.ForeignKey(Person, on_delete=models.SET_NULL, null=True)

    def save(self):
        super().save()
        return self.id

    
    def deleteRecordIgrow(self):
        super().delete()
        
   
class WorkshopSharing(models.Model):
    class Meta:
        db_table = 'WorkshopSharing'
    Title = models.CharField(max_length=255)
    Message = models.CharField(max_length=255)
    #Skill = models.CharField(max_length=20,default="")
    #State = models.CharField(max_length=100,default="")
    Photo = models.ImageField(upload_to ='uploads/', blank=True,null=True, default="")
    #Video = models.FileField(upload_to='uploads/', blank=True, null=True, default="")
    #created_at = models.DateTimeField(default=datetime.now, blank=True)
    #Creator_id = models.IntegerField()
    #Group = models.ForeignKey(Group_tbl, on_delete=models.CASCADE)
    Creator = models.ForeignKey(Person, on_delete=models.CASCADE)
    Workshop_id = models.ForeignKey(Workshop, on_delete=models.CASCADE)
    #Links = models.CharField(max_length=255)


    def save(self):
        super().save()
        #super().save(using='farming')
        return self.id

    def deleteRecordIgrow(self):
        super().delete()



class Booking(models.Model):
    class Meta:
        db_table = 'Booking'
    # Name = models.CharField(max_length=150)
    ProgrammeName = models.CharField(max_length=150,default="")
    Date = models.DateField()
    # Session = models.CharField(max_length=150)
    # nanti next version or bila share version ni, sila remove null=true okay
    BookWorkshop = models.ForeignKey(Workshop, on_delete=models.CASCADE, null=True)
    Participant = models.ForeignKey(Person, on_delete=models.SET_NULL, null=True)
    Messages = models.CharField(max_length=250, default="",null=True)

    def save(self):
        super().save()
        
        
    def deleteRecordIgrow(self):
        super().delete()
    
    class Meta:
        
        unique_together = [['BookWorkshop', 'Participant']]

class Inbox(models.Model):
    class Meta:
        db_table = 'inbox'
    Messages = models.CharField(max_length=250, default="",null=True)
    WorkshopTitle = models.CharField(max_length=250, default="",null=True)
    Participant = models.ForeignKey(Person, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(default=datetime.now, blank=True)
    #WorkshopFk = models.ForeignKey(Workshop, on_delete=models.CASCADE, null=True)
    is_read = models.BooleanField(default=False)

    def save(self):
        super().save()
        
    def deleteRecordIgrow(self):
        super().delete()

class WorkshopSoilTagging(models.Model):

    WorkshopSoilTag = models.ForeignKey(Workshop, related_name="soilTagging", on_delete=models.CASCADE)    
    soilTag = models.ForeignKey(SoilTag, on_delete=models.CASCADE)
   
    class Meta:  
        unique_together = [['WorkshopSoilTag', 'soilTag']]

    def save(self):
        super().save()
        
    def deleteRecordIgrow(self):
        super().delete()


class WorkshopPlantTagging(models.Model):

    WorkshopPlantTag = models.ForeignKey(Workshop, related_name="plantTagging", on_delete=models.CASCADE)    
    plantTag = models.ForeignKey(PlantTag, on_delete=models.CASCADE)
   
    class Meta:  
        unique_together = [['WorkshopPlantTag', 'plantTag']]

    def save(self):
        super().save()
        
    def deleteRecordIgrow(self):
        super().delete()

workshop/templates/PlantFilteredWorkshop.html
<!doctype html>
<html lang="en">

<head>
  <style>
    .content {
      max-width: 500px;
      margin: auto;
    }

    table {
      border: 4px solid black;
      margin: 0 auto;
      padding: 40px;
      width: fit-content;
      
    }

    .panel {
    margin-bottom: 30px;
    color: #696969;
    background-color: #fff;
    border-radius: 5px;
    box-shadow: 0 1px 5px rgba(0, 0, 0, 0.08);
}
  </style>
</head>

<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
  integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

<!-- <h1 class="p-3 mb-2 bg-success text-white text-center">iGROW Knowledge Management System</h1> -->

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
  integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
  integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js"
  integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>



<div class="pos-f-t">
  <div class="collapse" id="navbarToggleExternalContent">
    <div class="p-4" style="background-color: #8FBC8F;">
      <h4 class="text-white">What are you looking for?</h4>
      <span class="text-muted">Search here...</span>
      <form class="form-inline my-2">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-primary" type="submit">Search</button>
      </form>
    </div>
    
  </div>
  <nav class="navbar navbar-dark bg-success">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </nav>
</div>

<nav class="navbar navbar-expand navbar-dark bg-success">
  <a class="navbar-brand" href="#">P  L  A  N  T  F  E  E  D</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link " href="{% url 'Home' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'sharing:MainSharing' %}">Sharing</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href=" {% url 'group:MainGroup' %}">Group</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'MemberMainPage' %}">Member</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" href="{% url 'workshop:MainWorkshop' %}">Workshop</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Marketplace
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'marketplace:MainMarketplace' %}">Browse Marketplace<span class="sr-only">(current)</span></a>
          <a class="dropdown-item" href="{% url 'marketplace:MyMarketplace' %}">My Marketplace</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Profile
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'ViewProfile' %}">View Profile<span class="sr-only">(current)</span></a>
          <a class="dropdown-item" href="{% url 'EditProfile' %}">Edit Profile</a>
        </div>
      </li>

    </ul>
    <a class="btn bg-light" href="{% url 'Logout' %}">
      <img class="bi bi-arrow-bar-right">LOGOUT</img>
    </a>
  </div>
</nav>
<br />

  <div class="container my-3 bg-light" style="text-align: center;">
    <label for="exampleFormControlTextarea1" style="font-size: 2em;">Workshop</label>
  </div>
  <br />
  {% csrf_token %}
  {% block body %}

  {% if person.UserLevel == 'Admin' %}
  <div class="container">
    <!-- <a href="{% url 'workshop:CreateWorkshop' %}" class="link-primary">Create</a> ||
    <a href="{% url 'workshop:MyWorkshop' %}" class="link-primary">View Your Workshop</a> -->
    <a class="btn btn-primary" href="{% url 'workshop:CreateWorkshop' %}" role="button">Create Workshop</a>
    <a class="btn btn-primary" href="{% url 'workshop:MyWorkshop' %}" role="button">View Your Workshop</a>
  </div>
  {% endif %}

  <br />
  <div class="container">
    <h9>Filter based on tags: {{chosen_PlantTag.PlantTagName}}</h9>
  </div>
  <br />

  <div class="container">
    <form method="POST" class="center">
      {% csrf_token %}

      <br />
      <div class="row">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Programme Name</th>
              <th scope="col">Speaker</th>
              <th scope="col">Description</th>
              <th scope="col">Date</th>
              <th scope="col">Start Time</th>
              <th scope="col">End Time</th>
              <th scope="col">Plant Tagging Detail</th>
              <th colspan="2" style="text-align: center;" scope="col">Action</th>
              {% if person.UserLevel == 'User' %}
              <th scope="col"> &nbsp; </th>
              {% endif %}
            </tr>
          </thead>
          <tbody>
            {% csrf_token %}
            {% for data in filteredWorkshop %}
            <tr class="table">
              <th scope="row" value="{{ data.WorkshopPlantTag.ProgrammeName }}">{{ data.WorkshopPlantTag.ProgrammeName}}</th>
              <th scope="row" value="{{ data.WorkshopPlantTag.Speaker }}">{{ data.WorkshopPlantTag.Speaker }}</th>
              <th scope="row" value="{{ data.WorkshopPlantTag.Description }}">{{ data.WorkshopPlantTag.Description }}
              </th>
              <th scope="row" value="{{ data.WorkshopPlantTag.Date }}">{{ data.WorkshopPlantTag.Date }}</th>
              <th scope="row" value="{{ data.WorkshopPlantTag.StartTime }}">{{ data.WorkshopPlantTag.StartTime }}</th>
              <th scope="row" value="{{ data.WorkshopPlantTag.EndTime }}">{{ data.WorkshopPlantTag.EndTime }}</th>
              <th>
                {%for ori_workshop in ori_workshop %}

                {% if data.WorkshopPlantTag == ori_workshop %}


                {% if ori_workshop.soilTagging.all %}

                <i>
                  {% for soilTags in ori_workshop.soilTagging.all %}
                  {{soilTags.soilTag.SoilTagName}} {% if not forloop.last %},{% endif %}
                  {% endfor %}
                </i>
                {% endif %}

                {% if ori_workshop.plantTagging.all %}

                <i>
                  {% for plantTags in ori_workshop.plantTagging.all %}
                  {{plantTags.plantTag.PlantTagName}} {% if not forloop.last %},{% endif %}
                  {% endfor %}
                </i>
                {% endif %}

                {% endif %}

                {% endfor %}
              </th>
              {% if person.Email == data.WorkshopPlantTag.PIC.Email %}
              <!-- <th><a href="{% url 'workshop:UpdateWorkshop' data.WorkshopPlantTag.id %}" class="card-link">Edit</a></th>
              <th><a href="{% url 'workshop:DeleteWorkshop' data.WorkshopPlantTag.id %}" class="card-link">Delete</a></th> -->
              <th><a class="btn btn-secondary" href="{% url 'workshop:UpdateWorkshop' data.WorkshopPlantTag.id %}" role="button">Edit</a></th>
              <th><a class="btn btn-danger" href="{% url 'workshop:DeleteWorkshop' data.WorkshopPlantTag.id %}" role="button">Delete</a></th>
              {% else %}
              <th scope="row"> &nbsp; </th>
              <th scope="row"> &nbsp; </th>
              {% endif %}
              {% for booking in booking %}
            {% if  data.id == booking.BookWorkshop.id and booking.Participant.Email == request.session.Email %}
              <th><a href="{% url 'workshop:MainWorkshop' %}" class="btn btn-primary" role="button" onclick="return DuplicationWarning()">Booked</a></th>
            {% elif forloop.last %}
            <th><a href="{% url 'workshop:Booking' data.id %}" class="btn btn-primary" role="button" onclick="return ConfirmBooking()">Book</a></th>
              {% endif %}
            {%endfor%}

            {% if not booking %}
            <th><a href="{% url 'workshop:Booking' data.id %}" class="btn btn-primary" role="button" onclick="return ConfirmBooking()">Book</a></th>
            {% endif %}
            </tr>
            {% endfor %}
          </tbody>
        </table>

      </div>

    </form>
  </div>

  {% if not filteredWorkshop %}
  <hr>
  <div class="container">
    <h7 style="text-align: center;"><i>No workshop related to this {{ chosen_PlantTag.PlantTagName }} tag </i></h7>
  </div>
  <hr>
  {% endif %}


  {% endblock body %}
</body>

</html>